/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

/**
 *
 * @author Anahi
 */
public class VentanaAdministrarBodegas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaAdministrarBodegas
     */
    public VentanaAdministrarBodegas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBodega = new javax.swing.JLabel();
        lblCodigoB = new javax.swing.JLabel();
        lblNombreB = new javax.swing.JLabel();
        lblCiudadB = new javax.swing.JLabel();
        lblDireccionB = new javax.swing.JLabel();
        txtCodigoB = new javax.swing.JTextField();
        txtNombreB = new javax.swing.JTextField();
        txtCiudadB = new javax.swing.JTextField();
        txtDireccionB = new javax.swing.JTextField();
        btnAgregarB = new javax.swing.JButton();
        btnEliminarB = new javax.swing.JButton();
        btnEditarB = new javax.swing.JButton();
        btnCancelarB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBodega = new javax.swing.JTable();

        lblBodega.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblBodega.setText("Bodega:");

        lblCodigoB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCodigoB.setText("Código:");

        lblNombreB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNombreB.setText("Nombre:");

        lblCiudadB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCiudadB.setText("Ciudad:");

        lblDireccionB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDireccionB.setText("Dirección:");

        btnAgregarB.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarB.setText("Agregar");

        btnEliminarB.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnEliminarB.setText("Eliminar");

        btnEditarB.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnEditarB.setText("Editar");

        btnCancelarB.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnCancelarB.setText("Cancelar");

        tablaBodega.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tablaBodega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Ciudad", "Direccion"
            }
        ));
        jScrollPane1.setViewportView(tablaBodega);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBodega)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigoB)
                                    .addComponent(lblNombreB)
                                    .addComponent(lblCiudadB)
                                    .addComponent(lblDireccionB))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigoB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombreB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCiudadB)
                                    .addComponent(txtDireccionB, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnAgregarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarB)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarB))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBodega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigoB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombreB)
                        .addGap(18, 18, 18)
                        .addComponent(lblCiudadB)
                        .addGap(17, 17, 17)
                        .addComponent(lblDireccionB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodigoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCiudadB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDireccionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarB)
                    .addComponent(btnEliminarB)
                    .addComponent(btnEditarB)
                    .addComponent(btnCancelarB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarB;
    private javax.swing.JButton btnCancelarB;
    private javax.swing.JButton btnEditarB;
    private javax.swing.JButton btnEliminarB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBodega;
    private javax.swing.JLabel lblCiudadB;
    private javax.swing.JLabel lblCodigoB;
    private javax.swing.JLabel lblDireccionB;
    private javax.swing.JLabel lblNombreB;
    private javax.swing.JTable tablaBodega;
    private javax.swing.JTextField txtCiudadB;
    private javax.swing.JTextField txtCodigoB;
    private javax.swing.JTextField txtDireccionB;
    private javax.swing.JTextField txtNombreB;
    // End of variables declaration//GEN-END:variables
}
