/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;
import ec.edu.ups.dao.*;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import ec.edu.ups.controlador.*;
/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {
     private VentanaIniciarSesionUsuario ventanaIniciarSesion;
    private VentanaRegistroUsuarios ventanaRegistrarUsuario;
     private VentanaAdministrarBodegas gestionBodega;
     private VentanaAdministrarCliente gestionCliente;
     private VentanaAdministrarProducto gestionProducto;
     private VentanaInventarioBodega inventarioBodega;
     private VentanaInventarioDistribuidora inventarioDistribuidora;
     private VentanaPerfil perfil;
     private Factura factura;
     
    private UsuarioDao usuarioDao;
    private ClienteDao clienteDao;
    private ProductoDao productoDao;
    private BodegaDao bodegaDao;
    private FacturaDao facturaDao;
    private DetalleDao detalleDao;
    
    private ControladorUsuario controladorUsuario;
    private ControladorCliente controladorCliente;
    private ControladorProducto controladorProducto;
    private ControladorBodega controladorBodega;
    private ControladorFactura controladorFactura;
    private ControladorDetalle controladorDetalle;
    

   
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        btnAdministrar.setVisible(false);
        btnConsultar.setVisible(false);
        btnCerrarS.setVisible(false);
        btnIdioma.setVisible(true);
        
        usuarioDao = new UsuarioDao();
        clienteDao = new ClienteDao();
        productoDao = new ProductoDao();
        bodegaDao = new BodegaDao();
        facturaDao = new FacturaDao();
        detalleDao = new DetalleDao();
        
        controladorUsuario = new ControladorUsuario(usuarioDao);      
        controladorCliente = new ControladorCliente(clienteDao,facturaDao,detalleDao,productoDao);
        controladorProducto = new ControladorProducto (bodegaDao,productoDao);
        controladorBodega = new ControladorBodega(bodegaDao,productoDao);
        controladorFactura = new ControladorFactura(facturaDao,detalleDao,productoDao);
        controladorDetalle = new ControladorDetalle(detalleDao,productoDao);
       
        ventanaIniciarSesion = new VentanaIniciarSesionUsuario(controladorUsuario, this);
        ventanaRegistrarUsuario = new VentanaRegistroUsuarios(controladorUsuario);
        gestionBodega = new VentanaAdministrarBodegas  (controladorBodega); 
        gestionCliente = new VentanaAdministrarCliente  (controladorCliente);
        gestionProducto = new VentanaAdministrarProducto (controladorProducto,controladorBodega);
        inventarioBodega = new VentanaInventarioBodega  ();
        inventarioDistribuidora = new VentanaInventarioDistribuidora();
        perfil = new VentanaPerfil ();
        factura= new Factura ();
        
        
        
        
    }

    public JMenuItem getBntSalir() {
        return bntSalir;
    }

    public JMenu getBtnAdministrar() {
        return btnAdministrar;
    }

    public JMenuItem getBtnBodegas() {
        return btnBodegas;
    }

    public JMenuItem getBtnCerrarS() {
        return btnCerrarS;
    }

    public JMenuItem getBtnClientes() {
        return btnClientes;
    }

    public JMenu getBtnConsultar() {
        return btnConsultar;
    }

    public JMenuItem getBtnDeDistribuidora() {
        return btnDeDistribuidora;
    }

    public JMenuItem getBtnEs() {
        return btnEs;
    }

    public JMenuItem getBtnFacturas() {
        return btnFacturas;
    }

    public JMenu getBtnIdioma() {
        return btnIdioma;
    }

    public JMenuItem getBtnIngles() {
        return btnIngles;
    }

    public JMenuItem getBtnIniciarS() {
        return btnIniciarS;
    }

    public JMenu getBtnInicio() {
        return btnInicio;
    }

    public JMenuItem getBtnPerfil() {
        return btnPerfil;
    }

    public JMenuItem getBtnPorBodega() {
        return btnPorBodega;
    }

    public JMenuItem getBtnProductos() {
        return btnProductos;
    }

    public JMenuItem getBtnRegistrarU() {
        return btnRegistrarU;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnInicio = new javax.swing.JMenu();
        btnRegistrarU = new javax.swing.JMenuItem();
        btnIniciarS = new javax.swing.JMenuItem();
        btnCerrarS = new javax.swing.JMenuItem();
        bntSalir = new javax.swing.JMenuItem();
        btnAdministrar = new javax.swing.JMenu();
        btnBodegas = new javax.swing.JMenuItem();
        btnProductos = new javax.swing.JMenuItem();
        btnClientes = new javax.swing.JMenuItem();
        btnFacturas = new javax.swing.JMenuItem();
        btnPerfil = new javax.swing.JMenuItem();
        btnConsultar = new javax.swing.JMenu();
        btnPorBodega = new javax.swing.JMenuItem();
        btnDeDistribuidora = new javax.swing.JMenuItem();
        btnIdioma = new javax.swing.JMenu();
        btnIngles = new javax.swing.JMenuItem();
        btnEs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        btnInicio.setText("Inicio");

        btnRegistrarU.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        btnRegistrarU.setText("Registrar Usuario");
        btnRegistrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUActionPerformed(evt);
            }
        });
        btnInicio.add(btnRegistrarU);

        btnIniciarS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        btnIniciarS.setText("Iniciar Sesión");
        btnIniciarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSActionPerformed(evt);
            }
        });
        btnInicio.add(btnIniciarS);

        btnCerrarS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        btnCerrarS.setText("Cerrar Sesión");
        btnCerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSActionPerformed(evt);
            }
        });
        btnInicio.add(btnCerrarS);

        bntSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        bntSalir.setText("Salir");
        bntSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalirActionPerformed(evt);
            }
        });
        btnInicio.add(bntSalir);

        jMenuBar1.add(btnInicio);

        btnAdministrar.setText("Administrar");

        btnBodegas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        btnBodegas.setText("Bodegas");
        btnBodegas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBodegasActionPerformed(evt);
            }
        });
        btnAdministrar.add(btnBodegas);

        btnProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        btnAdministrar.add(btnProductos);

        btnClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        btnAdministrar.add(btnClientes);

        btnFacturas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        btnFacturas.setText("Facturas");
        btnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasActionPerformed(evt);
            }
        });
        btnAdministrar.add(btnFacturas);

        btnPerfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        btnAdministrar.add(btnPerfil);

        jMenuBar1.add(btnAdministrar);

        btnConsultar.setText("Consultar Inventario");

        btnPorBodega.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        btnPorBodega.setText("Por Bodega");
        btnPorBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorBodegaActionPerformed(evt);
            }
        });
        btnConsultar.add(btnPorBodega);

        btnDeDistribuidora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        btnDeDistribuidora.setText("De la Distribuidora");
        btnDeDistribuidora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeDistribuidoraActionPerformed(evt);
            }
        });
        btnConsultar.add(btnDeDistribuidora);

        jMenuBar1.add(btnConsultar);

        btnIdioma.setText("Idioma");

        btnIngles.setText("Inglés");
        btnIdioma.add(btnIngles);

        btnEs.setText("Español");
        btnIdioma.add(btnEs);

        jMenuBar1.add(btnIdioma);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
      jDesktopPane1.add(gestionProducto);
      gestionProducto.setVisible(true);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        jDesktopPane1.add(gestionCliente);
        gestionCliente.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
       jDesktopPane1.add(perfil);
       perfil.setVisible(true);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnIniciarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSActionPerformed
       jDesktopPane1.add(ventanaIniciarSesion);
       ventanaIniciarSesion.setVisible(true);
    }//GEN-LAST:event_btnIniciarSActionPerformed

    private void bntSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bntSalirActionPerformed

    private void btnRegistrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUActionPerformed
        jDesktopPane1.add(ventanaRegistrarUsuario);
        ventanaRegistrarUsuario.setVisible(true);
        btnIniciarS.setVisible(true);
        bntSalir.setVisible(true);
        btnAdministrar.setVisible(false);
        btnConsultar.setVisible(false);
        btnCerrarS.setVisible(false);
    }//GEN-LAST:event_btnRegistrarUActionPerformed

    private void btnCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSActionPerformed
       btnIniciarS.setVisible(true);
       btnRegistrarU.setVisible(true);
       btnAdministrar.setVisible(false);
       btnConsultar.setVisible(false);
       btnCerrarS.setVisible(true);
    }//GEN-LAST:event_btnCerrarSActionPerformed

    private void btnBodegasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBodegasActionPerformed
       jDesktopPane1.add(gestionBodega);
       gestionBodega.setVisible(true);
    }//GEN-LAST:event_btnBodegasActionPerformed

    private void btnPorBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorBodegaActionPerformed
       jDesktopPane1.add(inventarioBodega);
       inventarioBodega.setVisible(true);
    }//GEN-LAST:event_btnPorBodegaActionPerformed

    private void btnDeDistribuidoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeDistribuidoraActionPerformed
        jDesktopPane1.add(inventarioDistribuidora);
        inventarioDistribuidora.setVisible(true);
    }//GEN-LAST:event_btnDeDistribuidoraActionPerformed

    private void btnFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasActionPerformed
       jDesktopPane1.add(factura);
       factura.setVisible(true);
    }//GEN-LAST:event_btnFacturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bntSalir;
    private javax.swing.JMenu btnAdministrar;
    private javax.swing.JMenuItem btnBodegas;
    private javax.swing.JMenuItem btnCerrarS;
    private javax.swing.JMenuItem btnClientes;
    private javax.swing.JMenu btnConsultar;
    private javax.swing.JMenuItem btnDeDistribuidora;
    private javax.swing.JMenuItem btnEs;
    private javax.swing.JMenuItem btnFacturas;
    private javax.swing.JMenu btnIdioma;
    private javax.swing.JMenuItem btnIngles;
    private javax.swing.JMenuItem btnIniciarS;
    private javax.swing.JMenu btnInicio;
    private javax.swing.JMenuItem btnPerfil;
    private javax.swing.JMenuItem btnPorBodega;
    private javax.swing.JMenuItem btnProductos;
    private javax.swing.JMenuItem btnRegistrarU;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
